# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

	def create_user_for_osf(apps, schema_editor):
		User = apps.get_model("django.contrib.auth", "User")
		osf = User.objects.create(username='osf', password='a very secret password') # make api call to OSF to get password?
		

    dependencies = [
    ]

    operations = [
    	migrations.RunPython(create_user_for_osf),
    ]
